In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/covid_19_clean_complete_2022.csv")
df.drop('Province/State', axis=1, inplace=True)
df.head()

,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,Afghanistan,33.93911,67.709953,2020-01-22,0.0,0.0,0.0,0.0,Eastern Mediterranean
1,Albania,41.15330,20.168300,2020-01-22,0.0,0.0,0.0,0.0,Europe
2,Algeria,28.03390,1.659600,2020-01-22,0.0,0.0,0.0,0.0,Africa
3,Andorra,42.50630,1.521800,2020-01-22,0.0,0.0,0.0,0.0,Europe
4,Angola,-11.20270,17.873900,2020-01-22,0.0,0.0,0.0,0.0,Africa

In [4]:
df.isna().any()

Country/Region    False
Lat                True
Long               True
Date               True
Confirmed          True
Deaths             True
Recovered          True
Active             True
WHO Region         True
dtype: bool

In [5]:
df.describe()

,Lat,Long,Confirmed,Deaths,Recovered,Active
count,48409.000000,48408.000000,4.876000e+04,48760.000000,4.876000e+04,4.876000e+04
mean,20.532999,22.760273,1.307431e+04,759.706153,5.766604e+03,6.547998e+03
std,25.903779,76.319907,1.011426e+05,5688.360176,4.029688e+04,6.262942e+04
min,-71.949900,-178.116500,0.000000e+00,0.000000,0.000000e+00,-5.280000e+02
25%,6.428055,-42.604300,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
50%,22.300000,21.758700,1.020000e+02,1.000000,1.300000e+01,1.300000e+01
75%,41.204380,90.356300,1.068000e+03,19.000000,4.500000e+02,4.180000e+02
max,71.706900,178.065000,3.434802e+06,136862.000000,1.350098e+06,2.248842e+06

In [3]:
df.shape

(48761, 9)

In [6]:
df.dtypes

Country/Region     object
Lat               float64
Long              float64
Date               object
Confirmed         float64
Deaths            float64
Recovered         float64
Active            float64
WHO Region         object
dtype: object

In [7]:
df['Date'] = pd.to_datetime(df['Date'])
df['Country/Region'] = df['Country/Region'].astype('string')
df.dtypes

Country/Region            string
Lat                      float64
Long                     float64
Date              datetime64[ns]
Confirmed                float64
Deaths                   float64
Recovered                float64
Active                   float64
WHO Region                object
dtype: object

In [8]:
df = df.drop(['WHO Region','Country/Region'], axis=1)
df.head()

        Lat       Long       Date  Confirmed  Deaths  Recovered  Active
0  33.93911  67.709953 2020-01-22        0.0     0.0        0.0     0.0
1  41.15330  20.168300 2020-01-22        0.0     0.0        0.0     0.0
2  28.03390   1.659600 2020-01-22        0.0     0.0        0.0     0.0
3  42.50630   1.521800 2020-01-22        0.0     0.0        0.0     0.0
4 -11.20270  17.873900 2020-01-22        0.0     0.0        0.0     0.0